
export const SELECT_ARTIFACT = "SELECT_ARTIFACT";

export const GET_NODES = 'LOAD_NODES';
export const GET_SERVICES = "LOAD_SERVICES";
export const GET_NETWORKS = "LOAD_NETWORKS";


export const DELETE_NODE = 'DELETE_NODE';
export const UPDATE_NODE_LABELS = 'UPDATE_NODE_LABELS';